#CUDA_VISIBLE_DEVICES=0 celery -A tasks worker --pool=solo --loglevel=info
get_ipython().system('pip install -q -U pip')
get_ipython().system('pip install -r requirements.txt')
get_ipython().system('pip install -r requirements2.txt')
get_ipython().system('pip install langchain')
get_ipython().system('pip install multiprocess==0.70.15')
get_ipython().system('pip install -q -U bitsandbytes accelerate peft tensorboard')
get_ipython().system('pip uninstall markupsafe --yes')
get_ipython().system('pip install markupsafe==2.0.1')
get_ipython().system('export LD_LIBRARY_PATH="~/.local/lib/python3.10/site-packages/bitsandbytes:$LD_LIBRARY_PATH"')
get_ipython().system('python -m pip install python-dotenv')
get_ipython().system('pip install langchain_openai')
get_ipython().system('pip install langchain_google_openai')
get_ipython().system('pip install openai')
get_ipython().system('pip install google-api-python-client')
get_ipython().system('pip install "generative-ai-hub-sdk[google, amazon]"')
get_ipython().system('pip install langchain_google_genai')
#get_ipython().system('pip install -q torch==2.1.0a0+32f93b1')
#get_ipython().system('pip install -q peft==0.12.0')
#get_ipython().system('pip install -q jinja2==3.1.4')
#get_ipython().system('pip install -q datasets==2.20.0')
#get_ipython().system('pip install -q accelerate==0.33.0')
#get_ipython().system('pip install -q trl==0.9.6')
# get_ipython().system('pip install -q flask_restx')
# get_ipython().system('pip install -q flask-socketio')

get_ipython().system('pip install fastapi celery redis "uvicorn[standard]"')
get_ipython().system('pip install -q celery')
get_ipython().system('pip install -q redis')
get_ipython().system('pip install -q psycopg2')
get_ipython().system('pip install -U google-generativeai')
get_ipython().system('pip install -q openpyxl')
get_ipython().system('pip install -q flask_sqlalchemy')
get_ipython().system('pip install asyncpg')
get_ipython().system('pip install "fastapi[standard]"')
get_ipython().system('pip install langchain')
get_ipython().system('pip install langchain_community')
get_ipython().system('pip install pymilvus langchain pypdf PyMuPDF')
get_ipython().system('pip install langchain-huggingface')
get_ipython().system('pip install google-generativeai')
get_ipython().system('pip install boto3')
get_ipython().system('pip install faiss-cpu')
get_ipython().system('pip install tiktoken')
get_ipython().system('pip install selenium --upgrade ')
get_ipython().system('pip install --upgrade beautifulsoup4 lxml')
get_ipython().system('pip install webdriver-manager')
get_ipython().system('pip install numpy==1.23.5')
get_ipython().system('pip install sentence-transformers')
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
